apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-runner.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-runner.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "test-runner.name" . }}
    spec:
      containers:
        - name: test-runner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "tail -f /dev/null"]
